sudo: required
language: generic
matrix:
  include:
  - os: osx
    osx_image: xcode9.2
    language: generic
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
  - os: osx
    osx_image: xcode9.2
    language: generic
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=coverage
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=zpm
    - GCC_VERSION=7
global:
  env:
  - PROJECT=FileSystem
  - PROJECT_DIRECTORY={{PROJECT_DIRECTORY}}
  - PROJECT_TEMPLATE=latest
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/dev/script/install-zpm.sh)"
script:
- zpm run build-ci-library
after_success:
- zpm run deploy-ci-library
notifications:
  slack:
    secure: NY1UhbUmXq6s0q78bwC/X3l7De1T9m0XB359YuZVP00iytyqpphatnRVVlb8DxeHevUtoZgAQjz0B0w9jaMsqcD4nFebrdb/32M3soCEfG08KaxZgk2y12DisgkTZkEmwLvx88jtTBVna3FftJO4S3q7Rru1+RA9hngnMBg3J7bRwnkJUTG5+MHv5liRQn2e+j9I/AL3gyO3QjcTZt+/3xln1laEFEGjsIof64mtuwqLpW8Ii985zxqYUTiyY3t66kV59kwqRTc8fA9I066WOodr7WVPRmJkfYWTx7CbF5/XEw8mOKPxnJFKLXUbMXzMuZ52AkdOqsq73MPTumduFShP+JuBgqccB5aoYU3EDYF7AgOI5BXX/sEmlnz0AuEMZIoPtgkW2HrgIzELnxESNWYS08B5JwzdfGmLb+LbOfpcNN5TqTRJKGjl+Ugr3slAusNAMssfULYZLR66IiHcc1WXLa9z3rcceq9ra+tzTsTG17k2Zc4iWsPTmKp7gv0nYrE5AndknoZ5LGDpSxj4HZIbqvzdmzE9DHD+VFOKj8qOpVt4rVQhaNbT4QtinSThFFXOj25wRh+sCS4Gq0/sda1d7N0YO5tZJWIn3Qi24sn2sNP3OMtsUAHnWRm/RC5TIAi+wQ457h2TNLtFjBorAh4lIaV2e0cuXRcNAb2/zWs=
